Repository OpenCodeFoundation/eSchool, pull requests merged in 2021-10, with the labels that each got.

#518 Add docker files for ExamManageMent, ResultProcessing and LibraryManagement services
  docker-compose.override.yml
  docker-compose.yml
  eSchool.sln
  src/Services/ExamManagement/ExamManagement.API/Dockerfile
  src/Services/LibraryManagement/LibraryManagement.API/Dockerfile
  src/Services/ResultProcessing/ResultProcessing.API/Dockerfile
Labels: size/L

#525 fix(exam-management): fix build
  src/Services/ExamManagement/ExamManagement.API/ExamManagement.API.csproj
  src/Services/ExamManagement/ExamManagement.API/Program.cs
  src/Services/ExamManagement/ExamManagement.API/Startup.cs
Labels: size/M

#524 chore: update NuGet packages
  src/ApiGateways/eSchool.GraphQL/eSchool.GraphQL.csproj
  src/Services/CertificateProcessing/CertificateProcessing.API/CertificateProcessing.API.csproj
  src/Services/Enrolling/Enrolling.API/Enrolling.API.csproj
  src/Services/Enrolling/Enrolling.FunctionalTests/Enrolling.FunctionalTests.csproj
  src/Services/Enrolling/Enrolling.UnitTests/Enrolling.UnitTests.csproj
  src/Services/ExamManagement/ExamManagement.API/ExamManagement.API.csproj
  src/Services/LibraryManagement/LibraryManagement.API/LibraryManagement.API.csproj
  src/Services/ResultProcessing/ResultProcessing.API/ResultProcessing.API.csproj
  src/Web/Frontend.Blazor/Frontend.Blazor.Client/Frontend.Blazor.Client.csproj
  src/Web/Frontend.Blazor/Frontend.Blazor.Server/Frontend.Blazor.Server.csproj
Labels: size/L

#526 feat(pipeline): remove azure DevOps pipeline
  README.md
  build/azure-devops/enrolling-api/azure-pipelines.yml
  build/azure-devops/eschool-graphql/azure-pipelines.yml
  build/azure-devops/webstatus/azure-pipelines.yml
Labels: size/M

#528 release: cut the v0.9.0 release
  CHANGELOG.md
Labels: size/S
