Repository OpenCodeFoundation/eSchool, pull requests merged in 2021-07, with the labels that each got.

#456 chore(deps): bump OpenTelemetry from 1.0.0-rc5 to 1.0.0-rc6
  src/Libraries/OpenTelemetry/OpenTelemetry.csproj
Labels: size/XS

#471 feat(enrollment): use strongly typed ids
  .editorconfig
  build/dotnet/eSchool.ruleset
  eSchool.sln
  src/ApiGateways/eSchool.GraphQL/Enrollings/EnrollingQueries.cs
  src/ApiGateways/eSchool.GraphQL/Enrollings/EnrollmentMutations.cs
  src/ApiGateways/eSchool.GraphQL/OpenAPIs/Enrolling.json
  src/ApiGateways/eSchool.GraphQL/RestApiErrorMiddleware.cs
  src/ApiGateways/eSchool.GraphQL/Startup.cs
  src/ApiGateways/eSchool.GraphQL/eSchool.GraphQL.csproj
  src/Services/Enrolling/Enrolling.API/Application/Commands/EnrollmentApplicationCommand.cs
  src/Services/Enrolling/Enrolling.API/Application/Commands/EnrollmentApplicationCommandHandler.cs
  src/Services/Enrolling/Enrolling.API/Application/Queries/GetEnrollmentByIdHandler.cs
  src/Services/Enrolling/Enrolling.API/Application/Queries/GetEnrollmentByIdQuery.cs
  src/Services/Enrolling/Enrolling.API/Controllers/EnrollmentsController.cs
  src/Services/Enrolling/Enrolling.API/Enrolling.API.csproj
  src/Services/Enrolling/Enrolling.API/Startup.cs
  src/Services/Enrolling/Enrolling.API/graphql/EnrollingQuery.cs
  src/Services/Enrolling/Enrolling.API/graphql/GraphQlErrorFilter.cs
  src/Services/Enrolling/Enrolling.API/graphql/Mutation.cs
  src/Services/Enrolling/Enrolling.Domain/AggregatesModel/EnrollmentAggregate/Enrollment.cs
  src/Services/Enrolling/Enrolling.Domain/AggregatesModel/EnrollmentAggregate/EnrollmentId.cs
  src/Services/Enrolling/Enrolling.Domain/AggregatesModel/EnrollmentAggregate/IEnrollmentRepository.cs
  src/Services/Enrolling/Enrolling.Domain/Enrolling.Domain.csproj
  src/Services/Enrolling/Enrolling.Domain/SeedWork/Entity.cs
  src/Services/Enrolling/Enrolling.Infrastructure/Configuration/ValueConverters/EnrollmentIdValueConverter.cs
  src/Services/Enrolling/Enrolling.Infrastructure/Configuration/ValueConverters/ModelConfigurationBuilderExtensions.cs
  src/Services/Enrolling/Enrolling.Infrastructure/Enrolling.Infrastructure.csproj
  src/Services/Enrolling/Enrolling.Infrastructure/EnrollingContext.cs
  src/Services/Enrolling/Enrolling.Infrastructure/Repositories/EnrollmentRepository.cs
  src/Web/Frontend.Blazor/Frontend.Blazor.Client/.config/dotnet-tools.json
  src/Web/Frontend.Blazor/Frontend.Blazor.Client/.graphqlrc.json
  src/Web/Frontend.Blazor/Frontend.Blazor.Client/EnrollmentQuery.graphql
  src/Web/Frontend.Blazor/Frontend.Blazor.Client/Eschool.graphql
  src/Web/Frontend.Blazor/Frontend.Blazor.Client/Frontend.Blazor.Client.csproj
  src/Web/Frontend.Blazor/Frontend.Blazor.Client/Generated/.hash.md5
  src/Web/Frontend.Blazor/Frontend.Blazor.Client/Generated/Enrollment.cs
  src/Web/Frontend.Blazor/Frontend.Blazor.Client/Generated/EnrollmentId.cs
  src/Web/Frontend.Blazor/Frontend.Blazor.Client/Generated/EnrollmentQuery.cs
  src/Web/Frontend.Blazor/Frontend.Blazor.Client/Generated/EschoolClient.cs
  src/Web/Frontend.Blazor/Frontend.Blazor.Client/Generated/EschoolClientServiceCollectionExtensions.cs
  src/Web/Frontend.Blazor/Frontend.Blazor.Client/Generated/GetEnrollments.cs
  src/Web/Frontend.Blazor/Frontend.Blazor.Client/Generated/GetEnrollmentsOperation.cs
  src/Web/Frontend.Blazor/Frontend.Blazor.Client/Generated/GetEnrollmentsResultParser.cs
  src/Web/Frontend.Blazor/Frontend.Blazor.Client/Generated/IEnrollment.cs
  src/Web/Frontend.Blazor/Frontend.Blazor.Client/Generated/IEnrollmentId.cs
  src/Web/Frontend.Blazor/Frontend.Blazor.Client/Generated/IEschoolClient.cs
  src/Web/Frontend.Blazor/Frontend.Blazor.Client/Generated/IGetEnrollments.cs
  src/Web/Frontend.Blazor/Frontend.Blazor.Client/Generated/IRegisterStudent.cs
  src/Web/Frontend.Blazor/Frontend.Blazor.Client/Generated/RegisterStudent.cs
  src/Web/Frontend.Blazor/Frontend.Blazor.Client/Generated/RegisterStudentOperation.cs
  src/Web/Frontend.Blazor/Frontend.Blazor.Client/Generated/RegisterStudentResultParser.cs
  src/Web/Frontend.Blazor/Frontend.Blazor.Client/Pages/Enrollments/CreateEnrollment.razor
  src/Web/Frontend.Blazor/Frontend.Blazor.Client/Pages/Enrollments/Enrollments.razor
  src/Web/Frontend.Blazor/Frontend.Blazor.Client/Program.cs
  src/Web/Frontend.Blazor/Frontend.Blazor.Client/berry.json
  src/Web/Frontend.Blazor/Frontend.Blazor.Client/schema.extensions.graphql
  src/Web/Frontend.Blazor/Frontend.Blazor.Client/schema.graphql
  src/Web/Frontend.Blazor/Frontend.Blazor.Server/Controllers/AppSettingsController.cs
  src/Web/Frontend.Blazor/Frontend.Blazor.Server/Frontend.Blazor.Server.csproj
  src/Web/Frontend.Blazor/Frontend.Blazor.Shared/FrontendSettings.cs
Labels: size/XXL

#475 chore(deps): update NuGet packages version
  src/ApiGateways/eSchool.GraphQL/eSchool.GraphQL.csproj
  src/Libraries/OpenTelemetry/OpenTelemetry.csproj
  src/Services/CertificateProcessing/CertificateProcessing.API/CertificateProcessing.API.csproj
  src/Services/Enrolling/Enrolling.FunctionalTests/Enrolling.FunctionalTests.csproj
  src/Services/Enrolling/Enrolling.UnitTests/Enrolling.UnitTests.csproj
Labels: size/M

#413 Add how to run this application in visual studio
  README.md
Labels: size/XS

#427 Library Management Service initial implementation
  src/Services/LibraryManagement/LibraryManagement.API/Controllers/HelloWorldController.cs
  src/Services/LibraryManagement/LibraryManagement.API/LibraryManagement.API.csproj
  src/Services/LibraryManagement/LibraryManagement.API/Program.cs
  src/Services/LibraryManagement/LibraryManagement.API/Startup.cs
  src/Services/LibraryManagement/LibraryManagement.API/appsettings.Development.json
  src/Services/LibraryManagement/LibraryManagement.API/appsettings.json
Labels: size/L

#457 Feature/shahanaz/result processing/initial implemantion
  src/Services/ResultProcessing/ResultProcessing.API/Controllers/HelloWorldController.cs
  src/Services/ResultProcessing/ResultProcessing.API/Program.cs
  src/Services/ResultProcessing/ResultProcessing.API/ResultProcessing.API.csproj
  src/Services/ResultProcessing/ResultProcessing.API/Startup.cs
  src/Services/ResultProcessing/ResultProcessing.API/appsettings.Development.json
  src/Services/ResultProcessing/ResultProcessing.API/appsettings.json
Labels: size/L
